apiVersion: apps/v1
kind: Deployment
metadata:
  name: WebPage-qa
spec:
  selector:
    matchLabels:
      app: mercury-parser
      tier: backend
      track: stable
  replicas: 7
  template:
    metadata:
      labels:
        app: mercury-parser
        tier: backend
        track: stable
    spec:
      containers:
        - name: mercury-parser
          image: "gcr.io/qmul-lab/mercury-server:v1:1.0"
          ports:
            - name: http
              containerPort: 8080
