apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-qa
spec:
  selector:
    matchLabels:
      app: webpage-qa
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: webpage-qa
        tier: frontend
    spec:
      containers:
      - name: webpage-qa
        image: "gcr.io/qmul-lab/webpage-qa:v2"
        env:
        - name: ADMIN_TOKEN
          value: "VcLvN8mk2dDx_CwmYf4GHfF5A3ZArLbZcCu2NmGocfM"
        - name: API_BASE
          value: "https://d05c1717.ngrok.io/api"
