apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-qa
spec:
  selector:
    matchLabels:
      app: webpage-qa
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: webpage-qa
        tier: frontend
    spec:
      containers:
      - name: webpage-qa
        image: "gcr.io/qmul-lab/webpage-qa:v3.9"
        env:
        - name: ADMIN_TOKEN
          value: "NQxBmDWXHIJsV6KFa81UlLAW0tGwVfDQnESiYP_UAmU"
        - name: API_BASE
          value: "http://0e85c62d.ngrok.io/api"
