apiVersion: apps/v1
kind: Deployment
metadata:
  name: mercury-parser
spec:
  selector:
    matchLabels:
      app: mercury-parser
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mercury-parser
        tier: backend
    spec:
      containers:
        - name: mercury-parser
          image: "gcr.io/qmul-lab/mercury-server:v1"
          ports:
            - name: http
              containerPort: 8080
